### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by eveningkid** [joemcbride/YogaKit#1]
Hi Joe,

I would love to use your project for a Swift project.
Is there any way you could explain how to get it working for an existing project?

Thank you very much!

**Comment by joemcbride** [comment]
Hey, I’ve gotten it working with Carthage, though it did take some extra work.  That is mostly due to my lack of knowledge about properly creating frameworks that expose native headers.  Right now it may be easiest to copy the project into an existing one, which isn’t ideal.  It will work with Swift, just need to add the exposed headers to a bridging header.

```c
#import <yoga/YGMacros.h>
#import <yoga/YGEnums.h>
#import <yoga/Yoga.h>
#import <YogaKit/YGLayout.h>
#import <YogaKit/NSView+Yoga.h>
```

**Comment by joemcbride** [comment]
Commit of me playing with integration in a hybrid objc/Swift app.

https://github.com/joemcbride/outlander-osx/commit/662244bea9c494508b69409492ab91fb4c06f82b

**Comment by eveningkid** [comment]
Thank you for your time and the details, I'll get it working. :)
